baseURL = 'https://wiki.axekin.com/'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
title = 'Wiki of Axekin'
theme = 'reimu'

[languages]
  [languages.fr]
    languageName = 'Français'
    weight = 1
    title = 'Wiki de Axekin'
    contentDir = 'content/fr'
  [languages.en]
    languageName = 'English'
    weight = 2
    title = 'Wiki of Axekin'
    contentDir = 'content/en'

[outputs]
home = ["Algolia", "HTML", "RSS"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params]
  [params.algolia]
    appId = "TNLXPO3HD1"
    apiKey = "5f1e65f7434193c7d0acc69f14b424e8"
    indexName = "axekin"