baseURL = 'https://wiki.axekin.com/'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
title = 'Wiki of Axekin'
theme = 'reimu'

[languages]
  [languages.fr]
    languageName = 'Français'
    weight = 1
    title = 'Wiki de Axekin'
    contentDir = 'content/fr'
  [languages.en]
    languageName = 'English'
    weight = 2
    title = 'Wiki of Axekin'
    contentDir = 'content/en'